export enum ErrorCode {
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  FIELD_REQUIRED = 'FIELD_REQUIRED',
  INVALID_REQUEST = 'INVALID_REQUEST',
  INVALID_FIELD = 'INVALID_FIELD',
  ALREADY_EXISTED = 'ALREADY_EXISTED',
}
